#!/bin/sh

#Source functions
source $LUCI_ROOT/functions/zetta-tools

#Creating Docker host called luci-unittest
echo "Creating docker host called luci-unittest, please wait..."
runzettatools docker-machine-create luci-unittest

#Testing for docker host, with name luci-unittest
echo "The following output should show a string - Up and running"
runzettatools docker-machine ssh luci-unittest echo "Up and running"

#Removing docker host luci-unittest
echo "Cleaning up..."
runzettatools docker-machine rm -f luci-unittest
