#! /bin/sh

###
# Functionality to cleanup after test execution
###

CLEANUP_CONTAINERS=()
CLEANUP_IMAGES=()
CLEANUP_ACTIONS=()

# Stop and remove a docker container
# 1: Container name or id
function cleanup_container() {
    CLEANUP_CONTAINERS=(${CLEANUP_CONTAINERS[@]} $1)
}

# Delete a docker image
# 1: image name or id
function cleanup_image() {
    CLEANUP_IMAGES=(${CLEANUP_IMAGES[@]} $1)
}

# Add an action to perform during cleanup
# 1: Action to perform. This is simply a string representing the shell command
function cleanup_action() {
    CLEANUP_ACTIONS=(${CLEANUP_ACTIONS[@]})
}

### Create a temp dir that is deleted as part of cleanup
function cleanup_tempdir() {
    local name=$(tempdir)
    local action="rm -r $name"
    CLEANUP_ACTIONS=(${CLEANUP_ACTIONS[@]} action)
    echo $name
}

function timestamp() {
    date +%Y%m%d-%H%M%S.%s
}

# Perform the actual cleanup
function cleanup_perform() {
    echo "### BEGIN CLEANUP FOR $BATS_TEST_NAME ###"
    local testInfoDir="$LUCI_ROOT/build/testInfo/$BATS_TEST_NAME"
    rm -rf "$testInfoDir"
    mkdir -p "$testInfoDir"

    if [ -n "$CLEANUP_CONTAINERS" ] ; then
        local containers=${CLEANUP_CONTAINERS[@]}
        echo "Containers to cleanup: ${containers[@]}"
        CLEANUP_CONTAINERS=()
        for e in $containers ; do
            local dir="$testInfoDir/$e"
            echo "Deleting container: $e"
            mkdir -p $dir
            runZettaTools docker inspect $e > "$dir/inspect.json"
            #runZettaTools docker logs $e > "$dir/log.txt"
            docker logs $e > "$dir/log.txt"
            runZettaTools docker rm --volumes=true -f $e
        done
    fi

    for action in $CLEANUP_ACTIONS ; do
        eval "$action"
    done
    CLEANUP_ACTIONS=()

    if [ -n "$CLEANUP_IMAGES" ] ; then
        local images=${CLEANUP_IMAGES[@]}
        echo "Images to cleanup: ${images[@]}"
        CLEANUP_IMAGES=()
        for e in $images ; do
            echo "Deleting image: $e"
            runZettaTools docker rmi $e
        done
    fi

    if [ -f /tmp/luci-volumes.txt ] ; then
        echo "New volumes created by test $BATS_TEST_NAME"
        docker run --rm -v /var/lib/docker:/docker ubuntu:14.04 ls -1 /docker/volumes | grep -Fxv -f /tmp/luci-$BATS_TEST_NAME-volumes.txt
        echo "--- end ---"
        rm /tmp/luci-$BATS_TEST_NAME-volumes.txt
    fi

    dockerMachineReleaseAll

    cat $(ls -t1 $(realpath ${TMPDIR:-/tmp})/bats*.out | head -1) > "$testInfoDir/bats.log"
    echo "### END CLEANUP FOR $BATS_TEST_NAME ###"
}
