#! /bin/sh

. $LUCI_ROOT/functions/data-container

# Generate a data container with ssh keys
# 1: container name
keyPath=/data/praqma-ssh-key
function createSecretKeysContainer() {
    local containerName=$1
    local workdir=$(mktemp -d)
    ssh-keygen -t rsa -b 2048 -C "LUCI" -f $workdir/id_rsa -q -N ""
    createDataContainer $containerName $workdir $keyPath
    rm -r $workdir
}
