#! /bin/sh

# Generate a unique name
# 1: tag, a text included in name. Useful for debugging. Can be ommitted
function uniqueName() {
    echo "luci_$1_$RANDOM"
}

# We need to listen to the Jenkins output
# and wait untill both Jenkins and the jnlp
# is up af running. Set timeToRun in seconds
# to break a timeout.
# 1: defines the string we are looking for. The function will stop, when found.
# 2: timeout defined in seconds. 
function waitForLine() {
    local breakPoint=$1
    local timeToRun=$2

    local startTime=$(date +%s)
    local endTime=$(($startTime+$timeToRun))


    while read line; do
        if [ $(date +%s) -gt $endTime ]; then
          echo "Time out! ($timeToRun seconds waiting for '$breakPoint')"
          return 2
        fi
        case "$line" in
            *"$breakPoint"*) #TODO cleanup
                echo "Breakpoint found [$(date)]"
                return 0
                ;;
            *)
                ;;
        esac
    done
    echo "No more lines to read!"
    return 1
}
