###############################################################################
# Credentails file
###############################################################################
# Sure a lot of credentials a secrets is needed, and we don't want them in this
# configuration file. Thus supply the path of the file with the secrets.
# You can make sure that is available by some secure method.
# See example file secrets-example.yml for a configuration example.
# You can reference secrets by credentials.name and the content is replaced
# in the configuration file when parsing it.
credentials_file: secrets-example.yml


###############################################################################
# Hosting environment spefication
###############################################################################
# Where should the luci box run?
# You need to supply a docker host specification
# matching docker-machine syntax. https://docs.docker.com/machine/
# * You can run failure resilient and distribute load, pointing for example
#   to a docker swarm just like if it was a docker host
# * You can spread the load, or containers manually based on certain
#   requirements, by configuring multiple hosts and referring them in the 
#   service setup.
# * You can use any docker-machine supported driver, by using docker-machine.

# 'hosts' - optional. If not configured assume single local docker hosts (or already configured docker-machine).
hosts:
  # 'name' - optional. Name need to be used if you want to manually spread the services to named hosts.
  # Defaults to lucihost1, lucihost2, ...
# - name: my-ssh-host
    # 'configuration' - required to configure a host. Uses docker-machine configuration option, supply those needed  - minimum required for the chosen driver
#   configuration:
#     - driver: generic
#     - generic-ip-address: 188.166.124.110
#     - generic-ssh-user=root
#     - generic-ssh-key=privatekeyfile

# - name: digitaloceanhost
    # 'configuration' - required to configure a host. Uses docker-machine configuration option, supply those needed - minimum required for the chosen driver
#   configuration:
#     - driver: digitalocean
#     - digitalocean-access-token=credentials.mydigitaloceanaccesstoken





###############################################################################
# Services
###############################################################################
# What services to you want to run?
# Enable/disable by commenting, on the available default services.
# Add your own services, in the custom section. Custom services must be
# configured in the service custumizations.
# Workers are services that we need more than one of, eg. build slaves.

services:
#  - repistory
  - artifactmanagement
  - buildserver
custom-services:
  - changemanagement
workers:
  - static_buildslaves
  - dynamic_buildslaves




###############################################################################
# Service customizations
###############################################################################
# The following configuration section customized your services.
# The defaults are already filled in, but you can adjust them using the
# available configuration patterns using commenting to enable/disable.
# If container is an image file, the image will be build and tagged
# uninquely and pushed to a registry (automatically created if 
# you use image files) to host the build image. 'version' is used a prefix
# for the autogenerated version tag, if not empty.

buildserver:
  container: jenkinks
  version: 1.609.2
  plugins: Javadoc Plugin, PMD Plug-in, Jenkins Xvfb plugin, Static Analysis Collector Plug-in, FindBugs Plug-in, Jenkins JaCoCo plugin, Checkstyle Plug-in, Github Plugin

artifactmanagement:
  container: mattgruter/artifactory
  version: 3.5.2.1
  repositories:
    - MCDwJCI-continuous
    - MCDwJCI-stable
    - MCDwJCI-release

changemamangemet:
  container: viewpl/docker-trac/
  version: latest


static_buildslaves:
  container: ubuntu
  version: 14.04.2
  count: 5
  # 'ssh-post-config-file' optional, will run a script file supplied, over ssh to the server
  ssh-post-config: post-configuration-dynamic-slaves.sh
 

dynamic_buildslaves:
  container: myveryspecialubuntu.dockerfile
  version: myveryspecialubuntu
  count: 2
  # 'ssh-post-config-file' optional, will run a script file supplied, over ssh to the server
#  ssh-post-config: post-configuration-dynamic-slaves.sh




###############################################################################
# Private docker registry
###############################################################################
# If a docker images can not be found on the official docker hub the 
# private docker registry is tried.
# The official docker registry is always tried first.

registry:
#host:	registry.hq.praqma.net:5000
#username: credentials.registryuser
#password: credentials.registrypass




###############################################################################
# Misc configuration
###############################################################################

# lucibox admins mail group
# luci automatically configures the different services to send out warnings
# about failures, failed backup etcs. that those services support.
# You can supply one mail-address here: we suggest to use a mail-group.
luciboxadminsmail: luci-admin@praqma.net
